services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: myuser
    ports:
      - "3306:3306"
  tiny_oauth2_poc_a11n_server:
    depends_on:
      - mariadb
    build:
      context: ./tiny_oauth2_poc_a11n_server
    volumes:
      - ./tiny_oauth2_poc_a11n_server:/usr/src/app
    ports:
      - "8081:8081"
    command: cargo watch -x run